export const tabs: AppTab[] = [
  { name: "(home)", title: "Home", symbol: "house.fill" },
  { name: "calendar", title: "Calendar", symbol: "calendar" },
  {
    name: "exercises",
    title: "Exercises",
    symbol: "figure.strengthtraining.traditional",
  },
  {
    name: "statistics",
    title: "Statistics",
    symbol: "chart.line.uptrend.xyaxis",
  },
  { name: "profile", title: "Profile", symbol: "person.crop.circle" },
];

export const USER_DATA = {
  userId: "1234556789",
  name: "Anh Hao Nguyen",
  email: "nguyenanhhao090708@gmail.com",
  password: "(encrypted password)",
  profilePicture: "(path to profile picture)",
  workoutRoutine: [
    {
      id: "11",
      name: "On-the-Go",
      isActivated: true,
      description: "Plan a one-time workout whenever you're ready.",
    },
    {
      id: "22",
      name: "Weekly Fixed",
      description: "Keep your training consistent every single week.",
      isActivated: true,
      schedule: [
        {
          id: "1",
          day: "Monday",
          title: "Pull Day",
          time: "(date format)",
          exercises: [
            {
              name: "Bench Press",
              sets: [
                {
                  id: 1,
                  reps: 5,
                  weight: "BW",
                  type: "Warm-up",
                  note: "Add 5kg band",
                },
                {
                  id: 2,
                  reps: 5,
                  weight: "BW",
                  type: "Warm-up",
                  note: "Add 5kg band",
                },
                {
                  id: 3,
                  reps: 5,
                  weight: "BW",
                  type: "Warm-up",
                  note: "Add 5kg band",
                },
                {
                  id: 4,
                  reps: 10,
                  weight: "BW",
                  type: "Failure",
                  note: "",
                },
                {
                  id: 5,
                  reps: 9,
                  weight: "BW",
                  type: "Failure",
                  note: "",
                },
                {
                  id: 8,
                  reps: 5,
                  weight: "BW",
                  type: "Failure",
                  note: "",
                },
              ],
            },
            {
              name: "Chin-up",
              sets: [
                {
                  id: 1,
                  reps: 9,
                  weight: "BW",
                  type: "Failure",
                  note: "Add 5kg band",
                },
                {
                  id: 2,
                  reps: 8,
                  weight: "BW",
                  type: "Failure",
                  note: "Add 5kg band",
                },
                {
                  id: 3,
                  reps: 7,
                  weight: "BW",
                  type: "Failure",
                  note: "Add 5kg band",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: "22",
      name: "Cycle Flow",
      description: "Repeat your custom routine cycle after cycle..",
      isActivated: true,
      schedule: [
        {
          id: "1",
          time: "(date format)",
          title: "Pull Day",
          exercises: [
            {
              name: "Bench Press",
              sets: [
                {
                  id: 1,
                  reps: 5,
                  weight: "BW",
                  type: "Warm-up",
                  note: "Add 5kg band",
                },
                {
                  id: 2,
                  reps: 5,
                  weight: "BW",
                  type: "Warm-up",
                  note: "Add 5kg band",
                },
                {
                  id: 3,
                  reps: 5,
                  weight: "BW",
                  type: "Warm-up",
                  note: "Add 5kg band",
                },
                {
                  id: 4,
                  reps: 10,
                  weight: "BW",
                  type: "Failure",
                  note: "",
                },
                {
                  id: 5,
                  reps: 9,
                  weight: "BW",
                  type: "Failure",
                  note: "",
                },
                {
                  id: 8,
                  reps: 5,
                  weight: "BW",
                  type: "Failure",
                  note: "",
                },
              ],
            },
            {
              name: "Chin-up",
              sets: [
                {
                  id: 1,
                  reps: 9,
                  weight: "BW",
                  type: "Failure",
                  note: "Add 5kg band",
                },
                {
                  id: 2,
                  reps: 8,
                  weight: "BW",
                  type: "Failure",
                  note: "Add 5kg band",
                },
                {
                  id: 3,
                  reps: 7,
                  weight: "BW",
                  type: "Failure",
                  note: "Add 5kg band",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  measurements: {
    bodyWeight: [
      { date: "(date format)", weight: 70 },
      { date: "(date format)", weight: 72 },
      { date: "(date format)", weight: 74 },
      { date: "(date format)", weight: 76 },
    ],
    bodyFatPercentage: [
      { date: "(date format)", percentage: 15 },
      { date: "(date format)", percentage: 14 },
      { date: "(date format)", percentage: 13 },
      { date: "(date format)", percentage: 12 },
    ],
    currentWeight: 65,
    height: 167,
    bust: 95,
    waist: 75,
    hips: 90,
  },
  gender: 1,
  achievements: [
    {
      id: "1",
      type: "statistic",
      title: "Max dips",
      content: 20,
      change: "+2",
      unit: "reps",
      date: "(date format)",
    },
    {
      id: "2",
      type: "statistic",
      title: "Max push-ups",
      content: 50,
      change: "+2",
      unit: "reps",
      date: "(date format)",
    },
    {
      id: "3",
      type: "statistic",
      title: "Max pull-ups",
      content: 12,
      change: "+2",
      unit: "reps",
      date: "(date format)",
    },
  ],
  schedule: [
    {
      id: "1",
      title: "Pull Day",
      date: "(date format)",
      duration: "(date format)",
      routine: "Weekly Fixed",
      status: "Completed",
      percentageCompleted: 100,
      exercises: [
        {
          name: "Bench Press",
          sets: [
            {
              id: 1,
              reps: 5,
              weight: "BW",
              type: "Warm-up",
              note: "Add 5kg band",
            },
            {
              id: 2,
              reps: 5,
              weight: "BW",
              type: "Warm-up",
              note: "Add 5kg band",
            },
            {
              id: 3,
              reps: 5,
              weight: "BW",
              type: "Warm-up",
              note: "Add 5kg band",
            },
            {
              id: 4,
              reps: 10,
              weight: "BW",
              type: "Failure",
              note: "",
            },
            {
              id: 5,
              reps: 9,
              weight: "BW",
              type: "Failure",
              note: "",
            },
            {
              id: 8,
              reps: 5,
              weight: "BW",
              type: "Failure",
              note: "",
            },
          ],
        },
        {
          name: "Chin-up",
          sets: [
            {
              id: 1,
              reps: 9,
              weight: "BW",
              type: "Failure",
              note: "Add 5kg band",
            },
            {
              id: 2,
              reps: 8,
              weight: "BW",
              type: "Failure",
              note: "Add 5kg band",
            },
            {
              id: 3,
              reps: 7,
              weight: "BW",
              type: "Failure",
              note: "Add 5kg band",
            },
          ],
        },
      ],
      expectedResults: [
        {
          name: "Bench Press",
          sets: [
            {
              id: 1,
              reps: 5,
              weight: "BW",
              type: "Warm-up",
              note: "Add 5kg band",
            },
            {
              id: 2,
              reps: 5,
              weight: "BW",
              type: "Warm-up",
              note: "Add 5kg band",
            },
            {
              id: 3,
              reps: 5,
              weight: "BW",
              type: "Warm-up",
              note: "Add 5kg band",
            },
            {
              id: 4,
              reps: 10,
              weight: "BW",
              type: "Failure",
              note: "",
            },
            {
              id: 5,
              reps: 9,
              weight: "BW",
              type: "Failure",
              note: "",
            },
            {
              id: 8,
              reps: 5,
              weight: "BW",
              type: "Failure",
              note: "",
            },
          ],
        },
        {
          name: "Chin-up",
          sets: [
            {
              id: 1,
              reps: 9,
              weight: "BW",
              type: "Failure",
              note: "Add 5kg band",
            },
            {
              id: 2,
              reps: 8,
              weight: "BW",
              type: "Failure",
              note: "Add 5kg band",
            },
            {
              id: 3,
              reps: 7,
              weight: "BW",
              type: "Failure",
              note: "Add 5kg band",
            },
          ],
        },
      ],
    },
  ],
};

export const informationOptions: InformationOptionProps[] = [
  {
    id: 1,
    symbolName: "textformat",
    title: "Name",
  },
  {
    id: 2,
    symbolName: "birthday.cake.fill",
    title: "Birthday",
  },
  {
    id: 3,
    symbolName: "bell.fill",
    title: "Notifications",
  },
  {
    id: 4,
    symbolName: "person.crop.circle",
    title: "Profile picture",
  },
];